version: '3.5'

services:
  superset-api-layer:
    build: ../
    image: pnthusi/superset-api-layer:latest
    ports:
      - "${API_PORT:-8079}:8080"
    restart: unless-stopped
    environment:
      SUPERSET_USERNAME: ${SUPERSET_USERNAME}
      SUPERSET_PASSWORD: ${SUPERSET_PASSWORD}
      SUPERSET_PROVIDER: ${SUPERSET_PROVIDER}
      SUPERSET_INCLUDE_REFRESH_TOKEN: ${SUPERSET_INCLUDE_REFRESH_TOKEN}
      SUPERSET_API_BASE_URL: ${SUPERSET_API_BASE_URL}
      OPENMETADATA_URL: ${OPENMETADATA_URL}
      OPENMETADATA_JWT_TOKEN: ${OPENMETADATA_JWT_TOKEN}
      SUPERSET_DB_HOST: ${SUPERSET_DB_HOST}
      SUPERSET_DB_USERNAME: ${SUPERSET_DB_USERNAME}
      SUPERSET_DB_PASSWORD: ${SUPERSET_DB_PASSWORD}
      SUPERSET_DB_DATABASE: ${SUPERSET_DB_DATABASE}
      REPORTING_DB_HOST: ${REPORTING_DB_HOST}
      REPORTING_DB_USERNAME: ${REPORTING_DB_USERNAME}
      REPORTING_DB_PASSWORD: ${REPORTING_DB_PASSWORD}
      REPORTING_DB_DATABASE: ${REPORTING_DB_DATABASE}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_AUTH_ENABLED: ${MAIL_AUTH_ENABLED}
      MAIL_START_TLS: ${MAIL_START_TLS}
      MAIL_RECIPIENTS: ${MAIL_RECIPIENTS}